/*********************************************************************************************************
 *  Version             Date            Name                Description
 *  V1.0                06-05-2022      Dnyanesh            Add Method Implemented
 **********************************************************************************************************/
public with sharing class Calculator {
    public Calculator() {

    }

    public integer add(integer a, integer b){
        return a+b;
    }

}
