/*********************************************************************************************************
 *  Version             Date            Name                Description
 *  V1.0                06-05-2022      Dnyanesh            Add Method Implemented
==========================================================================================================
 * Name: Calculator
 * Author: Dnyanesh
 * Date 06-05-2022
 *********************************************************************************************************/

public with sharing class Calculator {
    public Calculator() {

    }

    public integer add(integer a, integer b){
        return a+b;
    }
}
